/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker/bindings.d.ts --env-interface CloudflareBindings --include-runtime false --strict-vars false` (hash: c6b316ef91df17931b5c576c7a760881)
interface __BaseEnv_CloudflareBindings {
	FILES: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_USERNAME: string;
	ADMIN_PASSWORD_HASH: string;
	SESSION_SECRET: string;
	LEAD_NOTIFY_TO: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_USERNAME" | "ADMIN_PASSWORD_HASH" | "SESSION_SECRET" | "LEAD_NOTIFY_TO">> {}
}
